lang = int(8) 
breed = int(3)
diep = float(1.5)
de_grootte = int(lang) * int(breed) * float(diep)
afvoeren = float(32.5)
afvoeren_prijs = float(de_grootte) * float(afvoeren)

uitgraven = int(25)
uitgraven_prijs = int(uitgraven) * float(de_grootte)
totaal_prijs = float(afvoeren_prijs) + float(uitgraven_prijs)
print("uitgraven:€",uitgraven_prijs) 
print("afvoeren: €", afvoeren_prijs)
print("totaal:€" , totaal_prijs) 